### ISSUE TITLE
Select a list of test cases not working with RobotFramework 4.0

### ISSUE THREAD

**Issue by veghdev** [Snooz82/robotframework-datadriver#40]
After update to robotframework_datadriver-1.1.1 and robotframework 4.0 I get an error message when I try to use DYNAMICTESTS command line variable.
If I run the robot file without DYNAMICTESTS argument every test case will run correctly.

I attach  a simple test.robot and test.csv which can be used to reproduce the problem.
[test.zip](https://github.com/Snooz82/robotframework-datadriver/files/6222537/test.zip)

python3 -m robot --variable 'DYNAMICTESTS:Test.test1' test.robot
[ ERROR ] Calling method '_start_suite' of listener 'DataDriver' failed: AttributeError: 'NoneType' object has no attribute 'name'

**Comment by Snooz82** [comment]
Hi @veghdev 

Thank you very much for this issue.
i fixed it in 1.1.2

The problem was the performance improvement and that i missed to add the suite as parent to the new test.
Please test it.

Cheers and Thanks again!

**Comment by veghdev** [comment]
Hello @Snooz82,

Thank you very much for the quick fix.
I tested it.
